import React, { useState } from 'react';
import { NavigationPath } from '../types';

interface ArchitectureViewProps {
  onNavigate: (path: NavigationPath, queryParam?: string) => void;
  onShowToast: (msg: string) => void;
}

export const ArchitectureView: React.FC<ArchitectureViewProps> = ({ onNavigate, onShowToast }) => {
  const [activeTab, setActiveTab] = useState<'diagram' | 'schemas' | 'api-sandbox'>('diagram');
  const [selectedSchema, setSelectedSchema] = useState<string>('knowledge_embeddings');
  const [sandboxEndpoint, setSandboxEndpoint] = useState<'/api/chat' | '/api/health' | '/api/documents/upload' | '/api/feedback'>('/api/chat');
  const [sandboxPayload, setSandboxPayload] = useState<string>(
    JSON.stringify({ query: 'Why did Project Phoenix choose PostgreSQL?', mode: 'strict', top_k: 5 }, null, 2)
  );
  const [sandboxResponse, setSandboxResponse] = useState<string | null>(null);
  const [isLoadingSandbox, setIsLoadingSandbox] = useState(false);

  const schemas: Record<
    string,
    {
      tableName: string;
      description: string;
      columns: Array<{ name: string; type: string; constraints: string; description: string }>;
      indexes: string[];
      sqlDdl: string;
    }
  > = {
    knowledge_embeddings: {
      tableName: 'knowledge_embeddings',
      description: 'Stores semantic chunk embeddings and dense vectors generated by the Hindsight RAG pipeline.',
      columns: [
        { name: 'id', type: 'UUID', constraints: 'PRIMARY KEY DEFAULT gen_random_uuid()', description: 'Unique chunk identifier' },
        { name: 'document_id', type: 'UUID', constraints: 'REFERENCES documents(id) ON DELETE CASCADE', description: 'Parent document foreign key' },
        { name: 'chunk_index', type: 'INTEGER', constraints: 'NOT NULL', description: 'Ordinal position of chunk within document' },
        { name: 'content', type: 'TEXT', constraints: 'NOT NULL', description: 'Raw textual passage of the chunk' },
        { name: 'embedding', type: 'vector(1536)', constraints: 'NOT NULL', description: 'Dense semantic vector embedding' },
        { name: 'metadata', type: 'JSONB', constraints: 'DEFAULT \'{}\'::jsonb', description: 'ADR tags, authority, project, author metadata' },
        { name: 'created_at', type: 'TIMESTAMPTZ', constraints: 'DEFAULT NOW()', description: 'Timestamp of ingestion' }
      ],
      indexes: [
        'CREATE INDEX idx_embeddings_hnsw ON knowledge_embeddings USING hnsw (embedding vector_cosine_ops);',
        'CREATE INDEX idx_embeddings_doc ON knowledge_embeddings (document_id);',
        'CREATE INDEX idx_embeddings_meta_gin ON knowledge_embeddings USING gin (metadata);'
      ],
      sqlDdl: `CREATE TABLE knowledge_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID REFERENCES documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    embedding vector(1536) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Fast approximate nearest neighbor search via pgvector HNSW
CREATE INDEX idx_embeddings_hnsw 
ON knowledge_embeddings 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);`
    },
    adr_decisions: {
      tableName: 'adr_decisions',
      description: 'Ratified and proposed Architecture Decision Records governing engineering platforms.',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', constraints: 'PRIMARY KEY', description: 'Unique ADR identifier (e.g. adr-042)' },
        { name: 'adr_number', type: 'VARCHAR(32)', constraints: 'UNIQUE NOT NULL', description: 'Canonical number (e.g. ADR-042)' },
        { name: 'title', type: 'VARCHAR(255)', constraints: 'NOT NULL', description: 'Title of the architecture decision' },
        { name: 'status', type: 'VARCHAR(32)', constraints: 'NOT NULL', description: 'Approved | In Review | Superseded' },
        { name: 'summary', type: 'TEXT', constraints: 'NOT NULL', description: 'High-level context and rationale summary' },
        { name: 'full_rationale', type: 'TEXT', constraints: 'NULL', description: 'Detailed technical specification and trade-offs' },
        { name: 'project_id', type: 'VARCHAR(64)', constraints: 'REFERENCES projects(id)', description: 'Associated initiative or project' },
        { name: 'ratified_by', type: 'VARCHAR(255)', constraints: 'NOT NULL', description: 'Review board or council' },
        { name: 'author_id', type: 'VARCHAR(64)', constraints: 'REFERENCES expert_profiles(id)', description: 'Primary author of the ADR' },
        { name: 'ratified_at', type: 'DATE', constraints: 'NULL', description: 'Formal sign-off date' }
      ],
      indexes: [
        'CREATE INDEX idx_adr_status ON adr_decisions (status);',
        'CREATE INDEX idx_adr_project ON adr_decisions (project_id);'
      ],
      sqlDdl: `CREATE TABLE adr_decisions (
    id VARCHAR(64) PRIMARY KEY,
    adr_number VARCHAR(32) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary TEXT NOT NULL,
    full_rationale TEXT,
    project_id VARCHAR(64) REFERENCES projects(id),
    ratified_by VARCHAR(255) NOT NULL,
    author_id VARCHAR(64) REFERENCES expert_profiles(id),
    ratified_at DATE
);`
    },
    projects: {
      tableName: 'projects',
      description: 'Strategic organizational projects and systems mapped into the knowledge graph.',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', constraints: 'PRIMARY KEY', description: 'Internal project ID' },
        { name: 'code', type: 'VARCHAR(32)', constraints: 'UNIQUE NOT NULL', description: 'Project code (e.g. PRJ-PHX)' },
        { name: 'name', type: 'VARCHAR(128)', constraints: 'NOT NULL', description: 'Initiative title' },
        { name: 'description', type: 'TEXT', constraints: 'NOT NULL', description: 'Strategic scope and mission' },
        { name: 'lead_id', type: 'VARCHAR(64)', constraints: 'REFERENCES expert_profiles(id)', description: 'Principal lead' },
        { name: 'tier', type: 'VARCHAR(32)', constraints: 'NOT NULL', description: 'Tier-1 Core | Tier-2 Critical' },
        { name: 'status', type: 'VARCHAR(32)', constraints: 'NOT NULL', description: 'Current milestone and release status' },
        { name: 'department', type: 'VARCHAR(128)', constraints: 'NOT NULL', description: 'Owning organizational unit' }
      ],
      indexes: ['CREATE INDEX idx_projects_code ON projects (code);'],
      sqlDdl: `CREATE TABLE projects (
    id VARCHAR(64) PRIMARY KEY,
    code VARCHAR(32) UNIQUE NOT NULL,
    name VARCHAR(128) NOT NULL,
    description TEXT NOT NULL,
    lead_id VARCHAR(64) REFERENCES expert_profiles(id),
    tier VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    department VARCHAR(128) NOT NULL
);`
    },
    expert_profiles: {
      tableName: 'expert_profiles',
      description: 'Domain authorities eligible for peer-consensus and knowledge calibration.',
      columns: [
        { name: 'id', type: 'VARCHAR(64)', constraints: 'PRIMARY KEY', description: 'Unique expert profile ID' },
        { name: 'name', type: 'VARCHAR(128)', constraints: 'NOT NULL', description: 'Full name' },
        { name: 'role', type: 'VARCHAR(128)', constraints: 'NOT NULL', description: 'Organizational title' },
        { name: 'department', type: 'VARCHAR(128)', constraints: 'NOT NULL', description: 'Department' },
        { name: 'accuracy_rate', type: 'NUMERIC(5,2)', constraints: 'NOT NULL', description: 'Historical consensus accuracy %' },
        { name: 'contributions_count', type: 'INTEGER', constraints: 'DEFAULT 0', description: 'Total verified reviews' },
        { name: 'specialties', type: 'TEXT[]', constraints: 'DEFAULT \'{}\'', description: 'Array of verified technical domains' }
      ],
      indexes: ['CREATE INDEX idx_experts_accuracy ON expert_profiles (accuracy_rate DESC);'],
      sqlDdl: `CREATE TABLE expert_profiles (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    role VARCHAR(128) NOT NULL,
    department VARCHAR(128) NOT NULL,
    accuracy_rate NUMERIC(5,2) NOT NULL,
    contributions_count INTEGER DEFAULT 0,
    specialties TEXT[] DEFAULT '{}'
);`
    },
    feedback_reinforcement_log: {
      tableName: 'feedback_reinforcement_log',
      description: 'Active human-in-the-loop corrections feeding back into the RAG memory graph.',
      columns: [
        { name: 'id', type: 'UUID', constraints: 'PRIMARY KEY DEFAULT gen_random_uuid()', description: 'Review ticket ID' },
        { name: 'ticket_number', type: 'VARCHAR(32)', constraints: 'UNIQUE NOT NULL', description: 'Reference key (e.g. KB-4921)' },
        { name: 'query_text', type: 'TEXT', constraints: 'NOT NULL', description: 'User question that triggered discrepancy' },
        { name: 'ai_output_before', type: 'TEXT', constraints: 'NOT NULL', description: 'Uncalibrated baseline response' },
        { name: 'corrected_text', type: 'TEXT', constraints: 'NOT NULL', description: 'Peer-reviewed authoritative fact' },
        { name: 'canonical_source', type: 'VARCHAR(255)', constraints: 'NOT NULL', description: 'Primary ADR or RFC reference' },
        { name: 'expert_id', type: 'VARCHAR(64)', constraints: 'REFERENCES expert_profiles(id)', description: 'Author of the correction' },
        { name: 'status', type: 'VARCHAR(32)', constraints: 'DEFAULT \'pending\'', description: 'pending | approved | rejected' },
        { name: 'applied_at', type: 'TIMESTAMPTZ', constraints: 'NULL', description: 'Timestamp when vectors were re-indexed' }
      ],
      indexes: [
        'CREATE INDEX idx_feedback_status ON feedback_reinforcement_log (status);',
        'CREATE INDEX idx_feedback_ticket ON feedback_reinforcement_log (ticket_number);'
      ],
      sqlDdl: `CREATE TABLE feedback_reinforcement_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_number VARCHAR(32) UNIQUE NOT NULL,
    query_text TEXT NOT NULL,
    ai_output_before TEXT NOT NULL,
    corrected_text TEXT NOT NULL,
    canonical_source VARCHAR(255) NOT NULL,
    expert_id VARCHAR(64) REFERENCES expert_profiles(id),
    status VARCHAR(32) DEFAULT 'pending',
    applied_at TIMESTAMPTZ
);`
    }
  };

  const handleRunSandbox = () => {
    setIsLoadingSandbox(true);
    setSandboxResponse(null);

    setTimeout(() => {
      let resp: Record<string, any> = {};
      if (sandboxEndpoint === '/api/chat') {
        resp = {
          status: 'success',
          latency_ms: 284,
          grounding_score: 0.964,
          model: 'llama-3.3-70b-versatile',
          provider: 'Groq Cloud LPU',
          pipeline: 'Hindsight RAG v2.4',
          citations: [
            { source: 'ADR-042', title: 'Database Architecture Decision', authority: 'Arch Review Board', similarity: 0.978 },
            { source: 'ENG-STD-12', title: 'ACID Consistency Protocol', authority: 'SecOps', similarity: 0.941 }
          ],
          response:
            'Project Phoenix selected PostgreSQL 15 as its primary relational store due to strict ACID requirements for transactional ledgers and native JSONB indexing for dynamic payment audit traces (ADR-042).'
        };
      } else if (sandboxEndpoint === '/api/health') {
        resp = {
          status: 'healthy',
          timestamp: new Date().toISOString(),
          uptime_percent: 99.98,
          subsystems: {
            fastapi: { status: 'ok', version: '0.111.0', workers: 4 },
            hindsight_rag: { status: 'ok', mean_recall: 0.962, stride: 64 },
            groq_llm: { status: 'ok', tokens_per_sec: 142.6 },
            pgvector: { status: 'ok', vector_count: 38419, index_type: 'HNSW' }
          }
        };
      } else if (sandboxEndpoint === '/api/documents/upload') {
        resp = {
          status: 'created',
          document_id: 'doc-89a1-43ef',
          chunks_created: 14,
          vector_dimensions: 1536,
          hindsight_index_status: 'SYNCHRONIZED',
          ingestion_duration_ms: 182
        };
      } else {
        resp = {
          status: 'accepted',
          ticket_number: 'KB-4922',
          verdict: 'queued_for_vector_reindex',
          message: 'Correction registered and queued for consensus propagation'
        };
      }

      setSandboxResponse(JSON.stringify(resp, null, 2));
      setIsLoadingSandbox(false);
      onShowToast(`Simulated ${sandboxEndpoint} execution completed successfully`);
    }, 450);
  };

  const handleEndpointSelect = (ep: typeof sandboxEndpoint) => {
    setSandboxEndpoint(ep);
    setSandboxResponse(null);
    if (ep === '/api/chat') {
      setSandboxPayload(
        JSON.stringify({ query: 'Why did Project Phoenix choose PostgreSQL?', mode: 'strict', top_k: 5 }, null, 2)
      );
    } else if (ep === '/api/health') {
      setSandboxPayload(JSON.stringify({ check_subsystems: true }, null, 2));
    } else if (ep === '/api/documents/upload') {
      setSandboxPayload(
        JSON.stringify(
          {
            filename: 'Kubernetes_Federation_RFC.md',
            category: 'Technical Spec',
            project: 'Platform Core',
            stride_tokens: 64
          },
          null,
          2
        )
      );
    } else {
      setSandboxPayload(
        JSON.stringify(
          {
            ticket_number: 'KB-4921',
            verified_by: 'Alex Morgan',
            canonical_source: 'ADR-042',
            correction_text: 'The Architecture Review Board officially approved PostgreSQL on March 12, 2024.'
          },
          null,
          2
        )
      );
    }
  };

  return (
    <div className="flex flex-col w-full animate-in fade-in duration-200">
      {/* Top Banner */}
      <section className="px-4 sm:px-6 lg:px-8 py-4 sm:py-5 border-b border-outline-variant/15 bg-surface-container-lowest">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-primary-fixed/30 text-primary font-mono-code text-[11px] font-semibold mb-2">
              <span className="material-symbols-outlined text-[13px]">account_tree</span>
              <span>ENGINEERING SPECIFICATION & PERSISTENCE MESH</span>
            </div>
            <h1 className="text-2xl lg:text-3xl font-bold text-on-surface tracking-tight font-display">
              System Architecture & Database Schemas
            </h1>
            <p className="text-sm text-on-surface-variant mt-1">
              End-to-end cognitive topology: FastAPI runtime, Hindsight RAG pipeline, Groq LLM inference, and pgvector schemas.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={() => onNavigate('system-health')}
              className="px-4 py-2 rounded-lg bg-surface-container-high hover:bg-surface-container-highest text-on-surface text-xs font-semibold flex items-center gap-2 border border-outline-variant/30 transition-all cursor-pointer shadow-xs"
            >
              <span className="material-symbols-outlined text-[16px] text-tertiary">dns</span>
              <span>System Health Telemetry</span>
            </button>
            <button
              onClick={() => onNavigate('ask', 'Explain the technical architecture of the Nexus organizational brain.')}
              className="px-4 py-2 rounded-lg bg-primary hover:bg-primary/95 text-on-primary text-xs font-semibold flex items-center gap-2 shadow-sm transition-all cursor-pointer"
            >
              <span className="material-symbols-outlined text-[16px]">forum</span>
              <span>Ask the Brain on Architecture</span>
            </button>
          </div>
        </div>

        {/* Tab switchers */}
        <div className="max-w-7xl mx-auto mt-6 flex items-center gap-3 border-b border-outline-variant/15">
          <button
            onClick={() => setActiveTab('diagram')}
            className={`pb-3 text-xs font-semibold flex items-center gap-2 border-b-2 transition-all cursor-pointer ${
              activeTab === 'diagram'
                ? 'border-primary text-primary'
                : 'border-transparent text-outline hover:text-on-surface'
            }`}
          >
            <span className="material-symbols-outlined text-[16px]">schema</span>
            <span>Interactive Architecture Topology</span>
          </button>
          <button
            onClick={() => setActiveTab('schemas')}
            className={`pb-3 text-xs font-semibold flex items-center gap-2 border-b-2 transition-all cursor-pointer ${
              activeTab === 'schemas'
                ? 'border-primary text-primary'
                : 'border-transparent text-outline hover:text-on-surface'
            }`}
          >
            <span className="material-symbols-outlined text-[16px]">database</span>
            <span>PostgreSQL & pgvector Schemas</span>
          </button>
          <button
            onClick={() => setActiveTab('api-sandbox')}
            className={`pb-3 text-xs font-semibold flex items-center gap-2 border-b-2 transition-all cursor-pointer ${
              activeTab === 'api-sandbox'
                ? 'border-primary text-primary'
                : 'border-transparent text-outline hover:text-on-surface'
            }`}
          >
            <span className="material-symbols-outlined text-[16px]">code</span>
            <span>Live FastAPI Endpoint Sandbox</span>
          </button>
        </div>
      </section>

      {/* Main Tab Content */}
      <section className="px-4 sm:px-6 lg:px-8 py-5 max-w-7xl mx-auto w-full">
        {/* TAB 1: INTERACTIVE TOPOLOGY DIAGRAM */}
        {activeTab === 'diagram' && (
          <div className="space-y-6">
            <div className="p-6 rounded-2xl bg-surface-container-lowest border border-outline-variant/20 shadow-xs">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-base font-bold text-on-surface">Cognitive Mesh Topology & Request Lifecycle</h3>
                  <p className="text-xs text-on-surface-variant mt-0.5">
                    Flow of user queries, semantic chunking, dense vector retrieval, high-speed LLM reasoning, and human verification.
                  </p>
                </div>
                <span className="font-mono-code text-[11px] px-2.5 py-0.5 rounded bg-surface-container font-semibold text-primary border border-outline-variant/30">
                  Uvicorn + FastAPI + Groq + pgvector
                </span>
              </div>

              {/* Topology SVG Flow */}
              <div className="w-full bg-surface-container-low/60 rounded-xl p-6 border border-outline-variant/20 overflow-x-auto">
                <div className="min-w-[850px] flex items-center justify-between gap-4">
                  {/* Node 1: Client UI */}
                  <div className="w-48 p-4 rounded-xl bg-surface-container-lowest border-2 border-primary/40 shadow-sm flex flex-col items-center text-center">
                    <div className="w-10 h-10 rounded-full bg-primary/10 text-primary flex items-center justify-center mb-2">
                      <span className="material-symbols-outlined text-[20px]">web</span>
                    </div>
                    <span className="font-bold text-xs text-on-surface">Client UI (SPA)</span>
                    <span className="text-[10px] text-outline font-mono-code mt-0.5">React 19 / Vite</span>
                    <p className="text-[10px] text-on-surface-variant mt-2">
                      Omni-Search, Citations, Expert Review Modals
                    </p>
                  </div>

                  <div className="flex flex-col items-center">
                    <span className="font-mono-code text-[10px] text-primary font-bold">POST /api/chat</span>
                    <span className="text-primary font-bold text-sm">➔</span>
                  </div>

                  {/* Node 2: FastAPI Gateway */}
                  <div className="w-48 p-4 rounded-xl bg-surface-container-lowest border-2 border-secondary/40 shadow-sm flex flex-col items-center text-center">
                    <div className="w-10 h-10 rounded-full bg-secondary/10 text-secondary flex items-center justify-center mb-2">
                      <span className="material-symbols-outlined text-[20px]">router</span>
                    </div>
                    <span className="font-bold text-xs text-on-surface">FastAPI Runtime</span>
                    <span className="text-[10px] text-outline font-mono-code mt-0.5">Python 3.11 / Uvicorn</span>
                    <p className="text-[10px] text-on-surface-variant mt-2">
                      Bearer Auth, Rate Limiter, Route Dispatcher
                    </p>
                  </div>

                  <div className="flex flex-col items-center">
                    <span className="font-mono-code text-[10px] text-secondary font-bold">Pipeline Invocation</span>
                    <span className="text-secondary font-bold text-sm">➔</span>
                  </div>

                  {/* Node 3: Hindsight RAG Engine */}
                  <div className="w-52 p-4 rounded-xl bg-surface-container-lowest border-2 border-tertiary/40 shadow-sm flex flex-col items-center text-center">
                    <div className="w-10 h-10 rounded-full bg-tertiary/10 text-tertiary flex items-center justify-center mb-2">
                      <span className="material-symbols-outlined text-[20px]">neurology</span>
                    </div>
                    <span className="font-bold text-xs text-on-surface">Hindsight RAG Engine</span>
                    <span className="text-[10px] text-outline font-mono-code mt-0.5">hindsight_rag.py</span>
                    <p className="text-[10px] text-on-surface-variant mt-2">
                      Reciprocal Rank Fusion, Cosine Grounding (0.96)
                    </p>
                  </div>

                  <div className="flex flex-col items-center">
                    <span className="font-mono-code text-[10px] text-tertiary font-bold">Vector & Context</span>
                    <span className="text-tertiary font-bold text-sm">➔</span>
                  </div>

                  {/* Node 4: Groq LLM Inference */}
                  <div className="w-52 p-4 rounded-xl bg-surface-container-lowest border-2 border-primary/40 shadow-sm flex flex-col items-center text-center">
                    <div className="w-10 h-10 rounded-full bg-primary/10 text-primary flex items-center justify-center mb-2">
                      <span className="material-symbols-outlined text-[20px]">bolt</span>
                    </div>
                    <span className="font-bold text-xs text-on-surface">Groq Cloud Inference</span>
                    <span className="text-[10px] text-outline font-mono-code mt-0.5">Llama 3.3 70B Versatile</span>
                    <p className="text-[10px] text-on-surface-variant mt-2">
                      142 tok/s, 230ms TTFT, Strict Hallucination Guard
                    </p>
                  </div>
                </div>

                {/* Sub-row: Persistence with pgvector */}
                <div className="mt-6 pt-6 border-t border-outline-variant/20 flex items-center justify-center">
                  <div className="w-full max-w-xl p-4 rounded-xl bg-surface-container-lowest border-2 border-primary/60 shadow-sm flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-primary-fixed/30 text-primary flex items-center justify-center shrink-0">
                      <span className="material-symbols-outlined text-[26px]">database</span>
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-xs text-on-surface">PostgreSQL 15 + pgvector Extension</span>
                        <span className="font-mono-code text-[10px] text-tertiary font-bold">HNSW Index Active</span>
                      </div>
                      <p className="text-[11px] text-on-surface-variant mt-0.5">
                        Stores 38,419 dense embeddings (1,536-dim vectors), ratified ADRs, project graphs, and verified human corrections.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Architecture Highlights Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              <div className="p-5 rounded-xl bg-surface-container-lowest border border-outline-variant/20">
                <div className="w-8 h-8 rounded-lg bg-primary-fixed/30 text-primary flex items-center justify-center mb-3">
                  <span className="material-symbols-outlined text-[18px]">verified</span>
                </div>
                <h4 className="font-bold text-sm text-on-surface">Zero-Hallucination Policy</h4>
                <p className="text-xs text-on-surface-variant mt-1 leading-relaxed">
                  Every answer produced by the brain is anchored to canonical ADRs and documentation with exact citations.
                  Low-confidence assertions trigger immediate flags.
                </p>
              </div>

              <div className="p-5 rounded-xl bg-surface-container-lowest border border-outline-variant/20">
                <div className="w-8 h-8 rounded-lg bg-secondary-fixed/40 text-secondary flex items-center justify-center mb-3">
                  <span className="material-symbols-outlined text-[18px]">cached</span>
                </div>
                <h4 className="font-bold text-sm text-on-surface">Continuous Learning Loop</h4>
                <p className="text-xs text-on-surface-variant mt-1 leading-relaxed">
                  When domain experts propose corrections, embeddings in pgvector are atomically re-indexed and re-weighted,
                  permanently improving organizational accuracy.
                </p>
              </div>

              <div className="p-5 rounded-xl bg-surface-container-lowest border border-outline-variant/20">
                <div className="w-8 h-8 rounded-lg bg-tertiary-fixed/30 text-tertiary flex items-center justify-center mb-3">
                  <span className="material-symbols-outlined text-[18px]">speed</span>
                </div>
                <h4 className="font-bold text-sm text-on-surface">Sub-Second Synthesis</h4>
                <p className="text-xs text-on-surface-variant mt-1 leading-relaxed">
                  Combining HNSW vector similarity indexes in PostgreSQL with Groq LPU processing yields complete multi-citation answers in under 350ms.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: DATABASE SCHEMAS */}
        {activeTab === 'schemas' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
            {/* Table Selector */}
            <div className="lg:col-span-4 bg-surface-container-lowest rounded-2xl border border-outline-variant/20 p-4 space-y-2">
              <span className="text-[10px] font-mono-code text-outline uppercase px-2 font-bold">
                POSTGRESQL RELATIONAL TABLES
              </span>

              {Object.keys(schemas).map((key) => {
                const isSelected = selectedSchema === key;
                return (
                  <button
                    key={key}
                    onClick={() => setSelectedSchema(key)}
                    className={`w-full text-left p-3 rounded-xl border transition-all cursor-pointer font-mono-code text-xs ${
                      isSelected
                        ? 'bg-primary-fixed/30 border-primary text-primary font-bold shadow-xs'
                        : 'bg-surface-container-low/40 border-outline-variant/20 text-on-surface hover:bg-surface-container-low'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span>{schemas[key].tableName}</span>
                      <span className="material-symbols-outlined text-[16px]">chevron_right</span>
                    </div>
                  </button>
                );
              })}
            </div>

            {/* Selected Table Inspector */}
            <div className="lg:col-span-8 bg-surface-container-lowest rounded-2xl border border-outline-variant/20 p-6 space-y-6">
              <div>
                <div className="flex items-center justify-between">
                  <h3 className="font-mono-code font-bold text-lg text-primary">
                    {schemas[selectedSchema].tableName}
                  </h3>
                  <span className="text-[10px] font-mono-code px-2 py-0.5 rounded bg-surface-container-high text-outline">
                    PostgreSQL 15
                  </span>
                </div>
                <p className="text-xs text-on-surface-variant mt-1">{schemas[selectedSchema].description}</p>
              </div>

              {/* Column Definitions Table */}
              <div>
                <h4 className="text-[11px] font-bold text-outline uppercase font-mono-code mb-2">Columns & Constraints</h4>
                <div className="border border-outline-variant/20 rounded-xl overflow-hidden">
                  <div className="grid grid-cols-12 bg-surface-container-high p-2.5 font-mono-code text-[11px] font-bold text-on-surface">
                    <div className="col-span-3">Column</div>
                    <div className="col-span-3">Type</div>
                    <div className="col-span-6">Constraints / Description</div>
                  </div>
                  {schemas[selectedSchema].columns.map((col, idx) => (
                    <div
                      key={col.name}
                      className={`grid grid-cols-12 p-2.5 border-t border-outline-variant/15 text-xs font-mono-code items-center ${
                        idx % 2 === 1 ? 'bg-surface-container-low/30' : ''
                      }`}
                    >
                      <div className="col-span-3 font-bold text-on-surface">{col.name}</div>
                      <div className="col-span-3 text-secondary font-medium">{col.type}</div>
                      <div className="col-span-6 text-on-surface-variant">
                        <span className="text-primary font-medium">{col.constraints}</span>
                        <span className="block text-[11px] text-outline font-sans mt-0.5">{col.description}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Indexes */}
              <div>
                <h4 className="text-[11px] font-bold text-outline uppercase font-mono-code mb-2">Indexes & Vectors</h4>
                <div className="space-y-1.5">
                  {schemas[selectedSchema].indexes.map((idx, i) => (
                    <div
                      key={i}
                      className="p-2.5 rounded-lg bg-surface-container-high font-mono-code text-[11px] text-on-surface border border-outline-variant/20"
                    >
                      {idx}
                    </div>
                  ))}
                </div>
              </div>

              {/* Full DDL */}
              <div>
                <h4 className="text-[11px] font-bold text-outline uppercase font-mono-code mb-2">SQL DDL Definition</h4>
                <pre className="p-4 rounded-xl bg-surface-container-high border border-outline-variant/20 font-mono-code text-xs text-on-surface overflow-x-auto leading-relaxed">
                  {schemas[selectedSchema].sqlDdl}
                </pre>
              </div>
            </div>
          </div>
        )}

        {/* TAB 3: LIVE API SANDBOX */}
        {activeTab === 'api-sandbox' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
            {/* Endpoint Selector & Request */}
            <div className="lg:col-span-6 bg-surface-container-lowest rounded-2xl border border-outline-variant/20 p-6 space-y-4">
              <div>
                <span className="text-[10px] font-mono-code text-outline uppercase font-bold">API ENDPOINT</span>
                <div className="grid grid-cols-2 gap-2 mt-2">
                  {(['/api/chat', '/api/health', '/api/documents/upload', '/api/feedback'] as const).map((ep) => (
                    <button
                      key={ep}
                      onClick={() => handleEndpointSelect(ep)}
                      className={`p-2.5 rounded-lg font-mono-code text-xs text-left transition-all cursor-pointer border ${
                        sandboxEndpoint === ep
                          ? 'bg-primary-fixed/40 border-primary text-primary font-bold'
                          : 'bg-surface-container-low border-outline-variant/20 text-on-surface hover:bg-surface-container'
                      }`}
                    >
                      {ep}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[10px] font-mono-code text-outline uppercase font-bold">Request Payload (JSON)</span>
                  <span className="font-mono-code text-[10px] text-outline">application/json</span>
                </div>
                <textarea
                  rows={8}
                  value={sandboxPayload}
                  onChange={(e) => setSandboxPayload(e.target.value)}
                  className="w-full p-3 bg-surface-container-high rounded-xl border border-outline-variant/20 font-mono-code text-xs text-on-surface focus:outline-none focus:ring-1 focus:ring-primary"
                />
              </div>

              <button
                onClick={handleRunSandbox}
                disabled={isLoadingSandbox}
                className="w-full py-2.5 rounded-xl bg-primary hover:bg-primary/95 text-on-primary font-semibold text-xs flex items-center justify-center gap-2 shadow-sm cursor-pointer disabled:opacity-50 transition-all"
              >
                <span className={`material-symbols-outlined text-[16px] ${isLoadingSandbox ? 'animate-spin' : ''}`}>
                  {isLoadingSandbox ? 'refresh' : 'play_arrow'}
                </span>
                <span>{isLoadingSandbox ? 'Executing Sandbox Request...' : 'Send Live Mock Request'}</span>
              </button>
            </div>

            {/* Response Output */}
            <div className="lg:col-span-6 bg-surface-container-lowest rounded-2xl border border-outline-variant/20 p-6 space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-mono-code text-outline uppercase font-bold">Server Response</span>
                {sandboxResponse && (
                  <span className="font-mono-code text-[10px] text-tertiary bg-tertiary-fixed/30 px-2 py-0.5 rounded font-bold">
                    HTTP 200 OK · 284ms
                  </span>
                )}
              </div>

              {sandboxResponse ? (
                <pre className="p-4 rounded-xl bg-surface-container-high border border-outline-variant/20 font-mono-code text-xs text-on-surface overflow-x-auto max-h-[380px] leading-relaxed">
                  {sandboxResponse}
                </pre>
              ) : (
                <div className="h-64 rounded-xl bg-surface-container-low border border-dashed border-outline-variant/30 flex flex-col items-center justify-center text-outline text-xs">
                  <span className="material-symbols-outlined text-[28px] mb-2">code</span>
                  <span>Select an endpoint and click Send Live Mock Request</span>
                </div>
              )}
            </div>
          </div>
        )}
      </section>
    </div>
  );
};
